server {
    listen 80;
    server_name web1.local;

    location / {
        root /usr/share/nginx/html/web1;
        index index.html;
    }
}

server {
    listen 80;
    server_name web2.local tnut.cuong.id.vn;

    location / {
        root /usr/share/nginx/html/web2;
        index index.html;
    }

    # Reverse proxy cho API Node-RED
    location /api/ {
        proxy_pass http://nodered:1880/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Cấu hình CORS
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
    }
}
